version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pracadyplomowa
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: ./
    ports:
      - 3006:3006
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/
      - /node_modules

volumes:
  db:
    driver: local
